spring:
  profiles: default
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: peimdb
      username: peiMongoUsr
      password: peiMongo17Pass
#Rabbitmq configuration
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: peirabbitmquser
    password: peirabbitmqpswd
    #virtual-host: sample
